apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: sso
spec:
  http:
    httpEnabled: true
  hostname:
    strict: false
    hostname: sso.redcomet.ca
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  serviceMonitor:
    enabled: true
  additionalOptions:
    - name: metrics-enabled
      value: "true"
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret
