apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: sso
spec:
  http:
    httpEnabled: true
    labels:
      release: kube-prometheus-stack
    annotations:
      ignore-check.kube-linter.io/privileged-container: "This deployment needs to run as privileged"
  hostname:
    strict: false
    hostname: sso.redcomet.ca
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  serviceMonitor:
    enabled: true
  additionalOptions:
    - name: metrics-enabled
      value: "true"
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret
