---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgA/h1z3JyTvl505hE1cOcDrNu2xxuKrjkzGxCWouMDApfq2KVBiwQ1fRo0bmXLXDvld2/qs7V3AMBylEfH+pB8MubGnLKg7k7j2zv5LTKbf3077inyn+Fv+XKSjy7CyOrrmRgLzjFeEl9K8fB8ufzf43p98dwL0yu0nh+Tdy4DAPKXaEZNCu2yL1uIDyxZ1Yt52EALpP8dzci7VGJ/fPQkQEddLf0lGi2+690N+8UbDSEa4S/6AOK62z8Lj6SqOZTP/krb/pxOcfP4irXnqGTPMfPijI5tBHmpskDgwg2e1PjygjclJFoN6qQbB7kaPHpfEoDHB1+hXNFIstH1cU6ZlZY9YkC/Csu4BDGTMvMaRSuXtpwU6AGxae1sWvzaAnsDilo7BsimezCyLUXNuIXtF4ozVjwKksmyB/5HcoElZHjp9Y/HoptD9YnIjKPWNEHlDFg9Td90nOVw9y+E/+mspQ2wUuCf1H/3csvc50pf6Kwazwvk/ftFjLFTaMuaWBzq31AlWjUm0MMOIxrvQyWGAP8uMMJrCEj0UmQuabkmWufYxNVq3YvSNNPSQLkudITzXk1OtDjp7/VBDnh2lekMxA9i0lk0ogatZzWPdZZznohbbwH9Dxe3lgTIY+loZ5uAoYiATJp3tz9GxqvzpYzp8E1+O2Iak8kqSJuRX8O0HO23VSpwxql8vp7A0F0XpCFFOtBM8OEKpe60lgZg=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
