apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: sso
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  http:
    httpEnabled: true
    labels:
      release: kube-prometheus-stack
  db:
    vendor: postgres
    passwordSecret:
      name: keycloak-db-secret
      key: password
    usernameSecret:
      name: keycloak-db-secret
      key: username
    url: jdbc:postgresql://keycloak-pg-rw/keycloak
    database: keycloak
  hostname:
    strict: false
    hostname: sso.redcomet.ca
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  serviceMonitor:
    enabled: true
  additionalOptions:
    - name: metrics-enabled
      value: "true"
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret
