---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: sso
spec:
  encryptedData:
    password: AgA84K3oieA3GkSrFQ0bglp2HLCXCZDBor15SGT9EZM9Mk2ABwND9y5yo3xG0qd2ftQue5RrsRnu95WcEJMW9fL19SpwIu3NkxXtkgxTiPUkICIQVn3f1JJfM5YB63HdphcLvGDbyejeLP4PBGpKK5np8bBDZ19obB/VMpESjfUhSSCBeZQDnrEtLfvJn+l3DJNat1hbW9Xm8d8HFI5VSecP1KEvZVkJH1iPD5vW6dcEWnMLW+g51Gt4nhyP/7I2C4rO89BzIrju9cuJaE+zbiB9QPaMCJ+kpt/cS9bpG3At1EX1iIy5cW8tigBkplYNNYhJ0pT4WFqkOhQpeX1fyh79/Hch66xyV3i1DfVM1FgZayn0pCGVrTzzlmAB3l+GOKn9nhxjGWEMxoQnYk4L5D3MFJ8VSeCzG82bdNmdJ49GaoO3T4cZaNnRHENR7PER+w7ft/sTKvLse5A+qrbJbd5UPG9wy0fRax/E8eRH30Uc3rXBHjlJ8QOFk5Ye6UomNuVI3fcpcmXkJsegNc4l3EIm2mJb+nJeJnGbZlZ+3Wqg6/u4NuLo7Als6Zfgwce0WE60ICdwAtZzYv6AO1mW8smAzxqfeqmxfGVWG4PUDI9n65TcB05dmXOFk8qMlNceWDgkJAZxhMu0I4Gh9+BOv6dqRZAVLJ9Z7F3ZaAgEDgg8j0fom6LL3hbLHhudcty+vY9ODeQ34NG6GEPS6Ds=
    username: AgAbugha+nV8uMigimB5DarwKLN9m/4CSFD3Ki8WX2p9qeA6Zdqtnd/VKbZqT8BZyTWWj8kFKYKBMhouXBwrLN0Wnsr3X/J63RUDPnU8ZK3DxUwtWprz3lAZY3RMLzCX8ObtLJryMD1oZS6ypO0L9IV3EkUqAdcn+kRORQjOE0ao+2QvOr84bkOcKZIIqxJW+Go6RsMB8l1sdpNFK5UmZ2P3TQiObA1R2hrQ9M85unVQgMcMgEWNxHIkCW+bYwaCki9tFjjDKbOKmq701LOk/Dsb17CSk9dsaAcB8M6Dtv+Onu/+ynsj2InhqCaS/F1mMQcrWXT6zRh5BbhHrb+mt5Zi5Xd8jsz3ntQL+gRb/O5J0UwaCBy91uEtkL7EC7Sk2YLYmsTOqOCUWJE8SALEk4fjQKcYpLHyT+VgRlXI1biEsOFMULXa6scDcoevqlSGOBui68UAGusbHGJV7cQ/OJHvqP2/E2dwYQsPMXce9Bz1EK5KCE3qJfsGLBa5sHzatJN3uVDyw1a7qaAvKMHfCTqm12XTsDbhp8jWBJ64qBchc4mAc/yJB7Ebid9wJJcrakZpMu/DkoyH59ehRgV6F9j8Tie0x+geK8fTVOEuRE+zH8lcXkZzUBRXRTPPd39k2PqgSVovpw51UHXEGc5O6DeABiJPjPshLX5TdB9M63p5d4bQWj6tuXhgywN0E9QAwUvzI1e5Ow==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: sso
