apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: keycloak
  namespace: sso
spec: {}
