apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    eck.k8s.elastic.co/license: basic
  name: kibana
  namespace: firewall
spec:
  config:
    server.publicBaseUrl: "https://kibana.redcomet.ca"
    csp.strict: false
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: firewall
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  secureSettings:
    - secretName: kibana-elasticsearch-credentials
  version: 9.1.2
