kind: Secret
apiVersion: v1
metadata:
  name: logstash-roles-secret
  namespace: firewall
stringData:
  roles.yml: |-
    eck_logstash_user_role:
      cluster: [ "monitor", "manage_ilm", "read_ilm", "manage_logstash_pipelines", "manage_index_templates", "cluster:admin/ingest/pipeline/get"]
      indices:
      - names: [ "pf-*", "unbound-*", "telegraf-*", "packetbeat-*" ]
        privileges: [ "auto_configure", "manage", "write", "create_index", "read", "view_index_metadata" ]
