apiVersion: batch/v1
kind: CronJob
metadata:
  name: set-es-replicas
  namespace: firewall
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: set-replicas
              image: curlimages/curl:latest
              env:
                - name: ES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: elasticsearch-es-elastic-user
                      key: elastic
              command:
                - /bin/sh
                - -c
                - |
                  ES_URL="https://elasticsearch-es-http:9200"
                  until [[ "${STATUS}" == "green" ]] || [[ "${STATUS}" == "yellow" ]]; do
                    STATUS=$(curl -s -k -u elastic:$ES_PASSWORD $ES_URL/_cat/health?h=status)
                    echo $STATUS
                    echo "Waiting for Elasticsearch to be ready..."
                    sleep 5
                  done
                  echo "Updating existing indices to 0 replicas..."
                  curl -k -u elastic:$ES_PASSWORD -X PUT $ES_URL/_all/_settings \
                    -H "Content-Type: application/json" \
                    -d '{
                      "index": {
                        "number_of_replicas": 0
                      }
                    }'
          serviceAccountName: default
