apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: jellyfin-config-backup
  namespace: k8up
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  tags:
    - jellyfin-backup
  backend:
    s3:
      endpoint: https://minio.redcomet.ca:9000
      bucket: k0s-backup
      accessKeyIDSecretRef:
        name: minio-credentials
        key: accessKey
      secretAccessKeySecretRef:
        name: minio-credentials
        key: secretKey
