apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: daily-schedule
  namespace: k8up
spec:
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: https://minio.redcomet.ca:9000
      bucket: k0s-backup
      accessKeyIDSecretRef:
        name: minio-credentials
        key: accessKey
      secretAccessKeySecretRef:
        name: minio-credentials
        key: secretKey
  backup:
    schedule: '0 0 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 3 * * *'
  prune:
    schedule: '0 4 * * *'
    retention:
      keepDaily: 14
