apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgBdl6rM+TV7jgouvbIlO+TyQy8NOYGSE9m0vGjEzxqaKtidP0FMtQdslLnroMT1qXGUYmmHI832z4pf1XbtXacK6QB/bPIbzaT45Cw/nPesKj3LCIZAcLs5T2LXylwOi8SQcSkiO7CCz2KkuT29Z6LsNR0/KxKFnGNHGYfjuyeoEz8H2yijOaoUeWGe9BXliI+VllCVJZsC5NiDUC2+49FH5nRbT9ZW+fe3oH+s2imjZuWNZo8UOfo9hA4bJHo7OzrfN62UZQiot20NZj6g3kI6d7/yeEag1fbRNHoTqAzC5RZGMBg38Vtoz84VCFml8Jk+ehDzqlU+ruJOx1drvyh0ueHzRv/xp3UNv93bCBF73DRNMD6cTgpbzdTqRf6jtO/b9VVbmovVn1XKv/wocYnGNQ8Ud/pudmGJghZaLUoe1GPCV6/jhryabpKzvKqtlGZgW33Nkhlx4a6W0ZZYrwhEdRHC4Wp7PXLjF7PraStm79ib9S90YbCAitpwq9Pyg+ERxoCA/DYLgu/Cn0OkHVWBpI90I+OMlI4UJFddmnVsoG1TrR78AlW4hyB2xL14T2TEIHyreo1pc4P4/WObd51ToULJE922Gj3NzGp1Ikzah/+bvrC9sovhMyvfg/nQxFY0pyKVavKxR/k4YVCRCDnOzzaVIWXpWF8CLPCuFm3H85mKA96jdzsz2sI/Bt0JUjSNF88GBQPHYd8eaa96qwVYTgfMJQiR1ePBRLRXKn4jCW0dkD/ZTckMxbb2G8QoVl7AE0uquUNx95O5ZD2YuM9EBea/J/nFOe6WcVHMrfSCaqH+xwtPkEZZ9ib3Us+e6qCVsNrISuLW/6ruzJqPq0Rx
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: velero
