[allowList]
  description = "Global AllowList"

  # Ignore SealedSecrets
  paths = [
    '''.*sealedsecret\.yaml$''',
    '''sealedsecret''',
    '''components\/apps\/argocd-repos\/gitea-repo\.yaml$''',
    '''components\/apps\/firewall\/kibana-es-credentials\.yaml$''',
    '''components\/apps\/vaultwarden\/yubico-sealedsecret\.yaml$''',
  ]
