[allowList]
  description = "Global AllowList"

  # Ignore SealedSecrets
  paths = [
    '''.*sealedsecret\.yaml$''',
    '''.*-sealedsecret\.yaml''',
    '''.*sealedsecret.*''',
    '''components\/apps\/argocd-repos\/gitea-repo\.yaml$''',
    '''components\/apps\/firewall\/kibana-es-credentials\.yaml$''',
    '''components\/apps\/vaultwarden\/yubico-sealedsecret\.yaml$''',
    '''components\/apps\/k8up-operator\/minio-sealedsecret\.yaml$''',
    '''components\/apps\/velero\/minio-sealedsecret\.yaml$''',
  ]
