apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`kuma.redcomet.ca`) && (PathPrefix(`/dashboard`) || PathPrefix(`/`))
    services:
    - kind: Service
      name: uptime-kuma
      port: 3001
