apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-data
  namespace: komga
  labels:
    app: komga
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
