apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`paperless.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: paperless-ngx
      port: 8000
