apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gotify
  namespace: gotify
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`gotify.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: gotify
      port: 8080
