apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openspeedtest
  namespace: openspeedtest
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`speedtest.redcomet.ca`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: speedtest-openspeedtest
          port: 3000
