apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`home.redcomet.ca`) && (PathPrefix(`/`) || PathPrefix(`/lovelace`))
    services:
    - kind: Service
      name: home-assistant
      port: 8123
