apiVersion: v1
kind: LimitRange
metadata:
  name: longhorn-memory-limit
  namespace: longhorn-system
spec:
  limits:
    - type: Container
      default:
        memory: 2Gi
      defaultRequest:
        memory: 500m
      max:
        memory: 4Gi
