apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-version-check-binding
  namespace: helm-version-check
  labels:
    apps: helm-version-check
subjects:
- kind: ServiceAccount
  name: helm-version-check
  namespace: helm-version-check
roleRef:
  kind: ClusterRole
  name: helm-version-check
  apiGroup: rbac.authorization.k8s.io
