apiVersion: v1
kind: Service
metadata:
  name: helm-version-check
  namespace: helm-version-check
  labels:
    app: helm-version-check
spec:
  selector:
    app: helm-version-check
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: metrics
