apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-version-check
  namespace: helm-version-check
  labels:
    release: kube-prometheus-stack
    app: helm-version-check
spec:
  selector:
    matchLabels:
      app: helm-version-check
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
