apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-grafan-helm
  namespace: argocd
stringData:
  name: grafana
  project: default
  type: helm
  url: https://grafana.github.io/helm-charts
