apiVersion: v1
stringData:
  name: minio
  project: default
  type: helm
  url: https://operator.min.io
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-minio
  namespace: argocd
type: Opaque
