apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`headlamp.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: headlamp
      port: 80
