---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: vaultwarden
spec:
  encryptedData:
    INSTALLATION_ID: AgBpPwibCTgVROoKbkpnrYJzEyyF5ylgCADFY1E7mjRHDFSghIHgcyvI92OxNrcTYi5LSLNFqdKpnYQWgibN9fcq3jqJ1FEDVz7/coesPq7fyDphrZnV77HWF/DjOwyMF4YByhe1Bmvwwbg8nNOiXECbXbPGEaEVgaogWdmfR13UAQjPYqMSIsZtLiQAQpTESSbO2bUwBa05Zw1CrS9GbYUYPwaxyZoQy/fXHnSWtMIesGnNcGNwJGC4UGa0I6XplsrVlKY3lgoUx6hm0DZhIhaB2cjdM4jXSTlEpsy3Ntt35DFvTev4jJWGH4nxuChfGwICl5dgRYOevMAxyWnV8XG4gKb+uYbEAswnMMTeWlxKjgjjoVSYiV2sZEeqRQEEmACZz61ijxgDneolYmhJz5+wl1jkAXOe6c8Z34kY/u0C99IVYMD6h6V4ekVaKAav7XNRvGiu1sK0oZf4ZjcJ56sf1RaXCHwDfpHBmyPX7CNus39MyEjoFFagJOuA6NhPbg3Dw2g9340NXuyDGc7nkhOo35RZCyfbziq5lygfko3juNX8bW7EzG/VLoBkN+wBXFywkOPjqKzFkSzjS7qO0eH3PnfsYruPlvqi81tkBjhvRoLdQs9VgeOgQrileAzIWAdU8eeUOnaFS2ZK/bZjE3Sl/94fSixqMPBbkGWmeh7hUVNhSnQiGTvYw3AJlaG7tGo/r0PY+MFKAmlv9IdAWvA0pD31H5DPHP0u/+fvStYSLLgJj5E=
    INSTALLATION_KEY: AgAND0nw45msTTl+UUJu2QvziSidBOBJVq0zT4KpueVuWNXVBAa7Nh+1r3HfnM/Nu4KEzbMxq8YvRRMzJpRzlkLjs82ZtUyksppWNrvuLuBmXfam1E7RXdrHyQ1QSHsN+aJVzyFpcD7yoSjvKYV/AU04PvN3pTKlg58RraWqxH12LCaiP+F65utLdZTXddU5eXJ+jC6cucOsj2eTMbdQfHgbDzDhhrNEzYLAPfF6pF/D+t0vRuzCAwsTDULDXGq/eC0DxaQ98GJnA3Z/WuLN4/RV8htw+k7EcHmw67moAtv3NHfcu5cKzBbKq4PhxnKAoUa9gDe9htri2LQMhnkOfpT8vlSwzwaVCIm8zx8QgphUkPC3cP8wjLbJVz42da2ZgQaYff/ERmjb6F+WQzKHNdpymyEdl2YCPjpMlfg2fvOncg9R1ZC72wMtbAYGgzIVsehXI9D4eDPG73vVCGbPdRML0fEkee/a114uhlxirE8m5fvF0Bg9sl04pp+ty+mw812JOvQ13r7LB88XoqRASGpHlo1FmqA5PehtO20uuPAbeNKDL9kkEVOqIJg8vMqMdMWe3pDv4zuqY7qNr1OOniVFklDfzzrgKuZ40HKRlMZf5BszbOhIt4kxINzhFaBbEfqkYtzRR1sci8ePRsW/cLopXJ46u0rkBOlTBsRd7qvXwvnn6sR67J+yvZe9Eux8rgfiLErmwZ74bSVAwU41OS0IbhEOiw==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: vaultwarden
