apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vaultwarden.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: vaultwarden
      port: 80
