---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgBx9Tzr4gaDN12NeEqWvFJVS/KGO2rRlahPfltQc6wGjNwvZ1euntjPgEVuP2cNi8Xw/lAzyhssA3hOOavmw/0+/4HbHoIIe4wE8sSlD7psLZGkenxK967eglu81szXp0jGeeNyexzl0bKAI4Nk4LYdF0DZeqWOIwRuiPRfKBQSyu3hJFzAC8CzL087lGAtgP1zfPCY7UN36QRFVwHabuQ9Zte5vgTpR/OFw0vN+YIabAxZsO3AwFgMhu9d0CBVcA1IbKIV8z64j5a6+Hj3TyQDG+lnUaJEeVhaYHBz0WAwLvaPysJJo2tbKEgvePD+4DhSCnVS3NRz5kGE3aTOi2bnJGD0x+6eFMlBohagDk1Bo7uQFBLwB8ACNING5CKrNZ8Nq/tLYUCOhNu/1es2P1l8Sac8fA9MzoanK2W3HcYAgBqcjN80B660pSxn8CcNK6g6J8kY9bf1QD8awi4aFHkMzkohQhvIY+JhYc02xoEyxUELdM9cHggDizUKJz3fcXxp6Qz/8hTZ3gDYcZaWUMIfnyH8R8oGmvTtxrnjlhbj/clI4zv/sQKwykWjzSIDIqfKCns+agIdLNFMt2VFYekyZMGxPSN+O/eRo6oOdvBm6/m0oXcpjG7ilYL99+Eypx0RDkEQ3KGfVZ7jbayYfrD0frWXhaA0KVqtDF6bWzpT3J1qYmS6UN1JKd61PnQ1bqFXt634zMQRBVZ9QTqxUUVrlPP14mVY9+VZV0CiWVAp28R7m+/boLzbEB/A8X/IHSove70scg479tnePw0TdsfXXQxzGXK6YPblAI1bm4NiJWZTCMcWgK8X/xBx+2NkbqvoSfVdAPHXPLCHHOtbZbjoLsQQEviyy8mFmLMwWc88ARQOK9ZzXVnXfZdxneVzG5MlRtGcT04ZpPPOhfk9Q6sgaoR53+zSQ9DlMv6ayWNDkxYHkyZXzDLjXirgeyw6j606AP/Db7qn3QvX1sOygzbFWYhesisuXJwK/JKAxJ7cZSKKVplbNXvqTg7Qd5XI+nAPyfqy88HJTduG5vbMg50y835YnCAIfoR+SJfeAyxSk22MO7RCkSd0iXzvVRdPp45SURotSr8/dGyYbpPJ3hMh5t38kMOWPWj0rdEWB9wXDUmDjw2e0VRIQqTYoVZDCBlsm65JviYoSFNf5gQmOEGdIBhjxQao6gc5lXQdidfU4dWfKrmWCxwo+tPCjN0tnV8mvzMt67NZ7LD/QMd2h9GLNJCKI0/F+Bbtq1N3ggEGQqQLBddGrt0EpEGgXpKOY9NUUsRLdRf9lCo0QUrxHOvZs8qTtzMaY7E7W8BUtUDopMjW+npZUHIhrotdNHZytWKcDn/StrL75WH8Imel6HkVjGsEmeskQufo0/EsAM7mvOfstpw8BtZUAv+pgtoJ
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring
    type: Opaque
