apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingressroute.yaml
- prom-ingressroute.yaml
- additional-scrape-configs.yaml
- mktxp-credentials-secret.yaml
- mktxp-deployment.yaml
