apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingressroute.yaml
- prom-ingressroute.yaml
- alertmanager-ingressroute.yaml
- alertmanager-sealedsecret.yaml
- additional-scrape-configs.yaml
- mktxp-credentials-sealedsecret.yaml
- mktxp-deployment.yaml
- longhorn-alerting-rules.yaml
