---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-keycloak-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgAc9tAhPsd1+mFdfdRlmlYZftgwRYDHCt6LrSSYxXPiwQi2f1C/oXsRr+H5dpV7RqKcO+exlnLVdFRvCAV0VrdltlW2WmobGMjepUOSON5kbnJ44QsdBcmhvKq7wJrNi83/S1OwZm0FDReHK53yH0I/oUxU/aTsL5kuMQG8WLln7eCYQf61xFB9TMw72ay9I9m7VmvhqXZI6QChQJv5Zq8tubXti+wMPKXnqyitxZDBvMHdbZc3/KzAqvtYEonltvKQA5JeI5FznyeY64WtVsSfKwgIYqKtVLFjNDxePtZtekljRdytGqPCD9BnS40c8oZdYv5di/4aVezDoXsuiLbmQMKnpr9BbqONHxuoIKvqWQNwv3vWQTCN5uBS5L/Adif/rLLPmG0r02moC8uy9iEHavlZlM8DpbXgP4XMZEuNcLpDfP5ANXHLI0Id/X4CduZ/wL7XzIh9yMNIFN0GqNRJ7RjCmynr/bk5WiBYPBOQLIDjP/iuO2c+XC6cXVmQAMLF3E+Vzl1QO9s6T+eciZJU70Bj42JJoYiulCl6mYaEk5L2/G0BeRbN8ehFvkaUtjWVkkoWKTuDmZRG1M3/ENDqrQMUfRQL3EtH0YFIeJ8Y28jpN3QxAdoB72kiOTzVesjkJGcBynj3ksu7LXV+olJ41gEMOuswd38mLsIK50QYn2PCDhVy0Hc0v2/6C7YPehL5PMxFPbXH
    client_secret: AgARb+N8Kkl7zQH+sF2bswi1Six4FsGcQz7msSNv8ZbBveeY46w9H/DLLEXHS5ke3GevldpSwOJvt+/3hcjxx+JT6iJGcaDsnGKCHRWou9SEZsdrhCB147zPQ1BAqNokzhCMwMZeUZr49jV5h+r2s7c7o9ErK4BKAlQ/mmG9LmWDp9nsoBRhXASBAgHE1PXkE4fhTMVR8ht0LhIyFyNvHWmK7wSSJpCHG+wj2GUFlit86YIdDu60dSyYd047Np+L7i/504jJpVJwz280e6uSmn+Au8IjACf5b0wckTZm/y8ToD74SRI32+QbJUV33gLboJJ38zVmcTZYt2e8gw0qxx9iCqX1eAqA6BExPCFJkGFn6M3qBOevGyoxec/vFluGxec9aNmcEKUkpQW10qIAoHNUqAytSjsHL+N5bGVqyRFG72BcXf8mVfasplknPfq3yffrTfMTa3+/EIDPZQvbDi0vL2y5Uy9OX0oyTX3MvhXKpSj+G9l9RpUcXL6XhRwyBXHQcR6uXGQSvXLyZcvt/Uappl8krZVLcORxLv9fz+yNNBndALJMLpSCSVCbf0a2cnmDl7M4iaEGvYB5aRGQ64JP4LNvTPa1JHKQTHaqWly9S9gmDPdZeDMb+5a9RN0QP064qcxSVewdId5S/2UMenGG6pFI8L9sgyLCHoDEfF5aqsaqKjPAbf142PQx8CtYtyLa2X2x/h+XzYcDu3KEJKVsOvV8q+9XkOy2e+Usf74JCQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-keycloak-secret
      namespace: monitoring
