---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  nfs:
    server: "172.16.0.55"
    path: "/mnt/rust/images/immich"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: longhorn-rwx
  volumeName: immich-pv-nfs
