apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: argo-cd
    helm:
      values: |-
        global:
          domain: "argocd.redcomet.ca"
        crds:
          install: true
          keep: true
        configs:
          cm:
            accounts.helm-version-checker: apiKey, login
          params:
            server.insecure: true
            server.disable.auth: false
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        dex:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        redis:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        server:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        applicationSet:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        notifications:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        rbac:
          policy.csv: |
            g, helm-version-checker, role:admin

    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.28
  - path: components/apps/argocd
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
    - CreateNamespace=true
