apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: firewall
  namespace: argocd
spec:
  destination:
    namespace: firewall
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: firewall
    path: components/apps/firewall
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  ignoreDifferences:
    - group: "elasticsearch.k8s.elastic.co"
      kind: "Elasticsearch"
      name: "elasticsearch"
      jsonPointers:
        - /metadata/annotations/eck.k8s.elastic.co~1orchestration-hints
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
