apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: gitea
    helm:
      parameters:
      - name: persistence.storageClass
        value: longhorn
      - name: postgresql-ha.enabled
        value: "false"
      - name: postgresql.enabled
        value: "true"
      - name: redis-cluster.enabled
        value: "false"
      - name: redis.enabled
        value: "true"
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.0
  - kustomize:
      namespace: gitea
    path: components/apps/gitea
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
