apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: gitea
    helm:
      values: |
        image:
          tag: 1.23.3-rootless
          rootless: true
        persistence:
          storageClass: longhorn
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
        redis-cluster:
          enabled: false
        redis:
          enabled: true
      parameters:
      - name: gitea.config.server.ROOT_URL
        value: https://gitea.redcomet.ca
      - name: gitea.config.server.DOMAIN
        value: gitea.redcomet.ca
      - name: gitea.config.server.SSH_DOMAIN
        value: gitea.redcomet.ca
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.0
  - kustomize:
      namespace: gitea
    path: components/apps/gitea
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
