apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: immich
    helm:
      values: |
        env:
          TZ: America/Edmonton
        redis:
          enabled: true
        persistence:
          dri:
            enabled: true
            type: hostPath
            hostPath: /dev/dri
          dma:
            enabled: true
            type: hostPath
            hostPath: /dev/dma_heap
          library:
            enabled: true
            type: pvc
            existingClaim: immich-library
            mountPath: /data/library
        postgresql:
          enabled: true
          primary:
            containerSecurityContext:
              readOnlyRootFilesystem: false
            initdb:
              scripts:
                create-extensions.sql: |
                  CREATE EXTENSION cube;
                  CREATE EXTENSION earthdistance;
                  CREATE EXTENSION vectors; 
        immich:
          persistence:
            library:
              existingClaim: immich-library
              enabled: true
              globalMounts:
                - path: /data/library
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.8.1
  - kustomize:
      namespace: immich
    path: components/apps/immich
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
