apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: immich
    helm:
      values: |
        env:
          TZ: America/Edmonton
        redis:
          enabled: true
        persistence:
          dri:
            enabled: true
            type: hostPath
            hostPath: /dev/dri
          dma:
            enabled: true
            type: hostPath
            hostPath: /dev/dma_heap
          library:
            existingClaim: immich-library
            enabled: true
            globalMounts:
              - path: /usr/src/app/upload
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.8.1
  - kustomize:
      namespace: immich
    path: components/apps/immich
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
