apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: jellyfin
    path: components/apps/jellyfin
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
