apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: jupyterhub
    helm:
      parameters:
      - name: nameOverride
        value: controller
      - name: proxy.service.type
        value: ClusterIP
      - name: hub.config.DummyAuthenticator.password
        value: jupyter
      - name: hub.config.Authenticator.admin_users
        value: crobb
    repoURL: https://hub.jupyter.org/helm-chart/
    targetRevision: 4.0.0
  - kustomize:
      namespace: jupyter
    path: components/apps/jupyter
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

