apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jupyterhub
    helm:
      parameters:
      - name: nameOverride
        value: controller
    repoURL: https://hub.jupyter.org/helm-chart/
    targetRevision: 4.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

