apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
spec:
  destination:
    namespace: memos
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: memos
    helm:
      values: |-
        image:
          tag: 0.24.1
        env:
          TZ: America/Edmonton
        mariadb:
          enabled: true
          primary:
            persistence:
              enabled: true
          auth:
            password: memos
            rootPassword: memos
        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            size: 8Gi
            storageClass: longhorn
    repoURL: https://charts.gabe565.com
    targetRevision: 0.17.0
  - kustomize:
      namespace: memos
    path: components/apps/memos
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
