apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
spec:
  destination:
    namespace: memos
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: memos
    helm:
      parameters:
      - name: mariadb.enabled
        value: "true"
      - name: mariadb.primary.persistence.enabled
        value: "true"
      - name: persistence.data.enabled
        value: "true"
      - name: mariadb.auth.password
        value: memos
      - name: mariadb.auth.rootPassword
        value: memos
      values: |-
        env:
          TZ: America/Edmonton
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 8Gi
            storageClass: longhorn
    repoURL: https://charts.gabe565.com
    targetRevision: 0.15.1
  - kustomize:
      namespace: memos
    path: components/apps/memos
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
