apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: openspeedtest
  namespace: argocd
spec:
  destination:
    namespace: openspeedtest
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: openspeedtest
      repoURL: https://openspeedtest.github.io/Helm-chart/
      targetRevision: 0.1.2
      helm:
        values: |
          service:
            type: ClusterIP
    - path: components/apps/openspeedtest
      repoURL: https://github.com/caseyrobb/k0s-gitops
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
