apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: tekton
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-operator
  project: default
  source:
    path: components/apps/tekton
    repoURL: https://github.com/caseyrobb/k0s-gitops
    targetRevision: HEAD
  ignoreDifferences:
    - group: "apiextentions.k8s.io"
      kind: "CustomResourceDefinition"
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
