apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-checker
  namespace: argocd
spec:
  destination:
    namespace: version-checker
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: version-checker
    repoURL: https://charts.jetstack.io
    targetRevision: v0.9.2
    helm:
      values: |
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        versionChecker:
          logLevel: info
          testAllContainers: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
