apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-argo-helm
  namespace: argocd
stringData:
  name: argo
  project: default
  type: helm
  url: https://argoproj.github.io/argo-helm
