apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: argocd-cm
  namespace: argocd
data:
  accounts.helm-version-checker: apiKey, login
