apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-gitea-helm
  namespace: argocd
stringData:
  name: gitea
  project: default
  type: helm
  url: https://dl.gitea.com/charts/
