apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-headlamp-helm
  namespace: argocd
stringData:
  name: headlamp
  project: default
  type: helm
  url: https://headlamp-k8s.github.io/headlamp/
