apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-jetstack-helm
  namespace: argocd
stringData:
  name: jetstack
  project: default
  type: helm
  url: https://charts.jetstack.io
