apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jupyter
  namespace: jupyter
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`jupyter.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: proxy-public
      port: 80
