apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docmost
  namespace: docmost
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`docmost.redcomet.ca`) || PathPrefix(`/`))
    services:
    - kind: Service
      name: docmost
      port: 3000
