apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: dlna
  namespace: jellyfin
spec:
  entryPoints:
    - dlna
  routes:
  - services:
    - name: jellyfin-dlna
      port: 1900
      #weight: 10
      #nativeLB: true
      #nodePortLB: true
