apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin-metrics
  namespace: jellyfin
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: jellyfin
  namespaceSelector:
    matchNames:
      - jellyfin
  endpoints:
    - interval: 15s
      port: metrics
