apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin-metrics
  namespace: jellyfin
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: jellyfin
  endpoints:
    - interval: 10s
      port: metrics
      path: /metrics
