---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgA/8Opkk4d2eFSuYdNHYcwgZpB5+XgWxZ4/M/KhVRzItGazH8wW1BFul2EahBfCNpIDm4KQ6r99JVBUfEq1LTzKwkOstIeGSkcA9OlQ4Eap/+JA6WWWUGeQDbnLaYH2V+PINyBzrM8w4X/mYndyhAPgJm9YTJinGPo0OkHrk7RT7qZfN5To+Z3zjeMi1kp+IvhGmNL7WM8CpL9RGS3p/xc5/QXKbH0quZMgRG0GsCxtDFuDw232svNxO+OK+s4uMfOxrtBcPy6pCEUNM3DeNHCBGXGWcs1Lbr6cnsJ3fzXs4gtw2KY9yIymyuOO2T6o11h6beIZ+Q2jrNbQsRIdbZOUkvZitm3hNDLZaesqgsFY0GCZTWoZvl7x90F959GFbR5sBE/IA+FnE8DGh/l0CwbOEGOlzSF3+G/lDMStWJIMfSkywab2dIeP7ecx2t9QC6/VXYdthCbkZzTgHnKroC3hyeIRjApz9etJ8cRMqTO4V9ZHzxrMfpva2vdtMR8JAxJf+n5ziJoojGvGU95ZSGxUyZorEJU6z/76K1SIU5ofQmEIQu1zIXWy4NPlO0zYIbakrDCQnyHJM+HjGI5+5ZxyNp+cFHo4c7B9e2JGleLYIoVwHD7pH4cIkora+vgbqZOJ++5X39FMtVuGmNehPnGDqvWiHdddU/ItjX19IbvSTGt0HHwDWqZUQXANeUTYkWAVh4lHa5/Bk+G7R8M70sE8OVehfg==
    RUSTFS_SECRET_KEY: AgCz6JO/tZ2AmqVTkMj3Bup27qGQlT76wH9IoNcPYFToWGoyS3vXK51hdmvb7Sbr4q6vw4vNq4p1r0A3nYP86tBzuXLU0vLfRGT/nm1BI+5jCRYJC5WC3S03t8LSxUhGJxOQBrNOTEJXxClB6RN7QvUslW/bXzpySmcEu3TqLAPNwwQFGkjTOnf30YRpglBebw1CC3wqiczyEgAEwVPCTvNpJR23XelYlgebLCzV0EQcfmFxY39V0J1FutVKRFAvMbB1G7VPbedVkX7/JpM2ntTIVg3K647Uo9H9/s3mwsoSepnKJD7+h0OBn0/bmpoIoAiSgUjZ8lftakg4EXO9IjeZfvpo2fHq2SyNbMBDfgDm7jN38SrmuMdJVaqO9QRmIn/UzVlG/H9/osqK+k1LSMDdmcF+xY3e7ZtK94TBu3WebjOJmOTdjb4jIqJABDCZkxHy6sn3RIBI15bOKFOaNcC3tan/r6jEOvEbYEluTgbTKnbCTra+qalc3iHAfM/mSlBzh5b50zeFGmPpG+IZWK/gM22KvEmg78ZO9Ue46wQzdkA3xwKagyDGze6q4Zf3ozmMBdymUNF5CnCzT6+tvmZH+Ems/WAj5gkDJ7FuqFB5OHa8i/Qg4rNqOP8OuNiSWKPeQm44mN47Y10UEQbIQTPZlQqJKuvDRVYDd0mBvlLoF2SpP22n7q8xGAhpwde+P3g+7FjOHKkT99+dFyCnziEWnp4Df98ba+e4fIGSZJL4Exaz0HGBvKo/
  template:
    metadata:
      creationTimestamp: null
      name: rustfs-secret
      namespace: rustfs
