replicaCount: 1

image:
  rustfs:
    tag: rustfs/rustfs:1.0.0-alpha.90

secret:
  existingSecret: rustfs-secret

config:
  volumes: "/data/rustfs0"
  region: "ca-west-1"
  log_level: info

mode:
  standalone:
    enabled: true
  distributed:
    enabled: false

storageclass:
  name: iscsi-fenrir
  dataStorageSize: 100Gi
  logStorageSize: 1Gi

ingress:
  enabled: false

hosts:
  - host: s3.redcomet.ca
    paths:
      - path: /
        pathType: Prefix
