apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`tekton.redcomet.ca`) && (PathPrefix(`/`) || PathPrefix(`/tekton`))
    services:
    - kind: Service
      name: tekton-dashboard
      port: 9097
