apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, helm-version-checker, role:admin
