apiVersion: v1
data:
  accounts.helm-version-checker: apiKey, login
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.redcomet.ca/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  url: https://argocd.redcomet.ca
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    app.kubernetes.io/instance: argocd-config
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
