apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  roles:
  - groups:
    - /argocd-admins
    name: argocd-admins
    policies:
    - p, proj:default:argocd-admins, applications, *, default/*, allow
  sourceRepos:
  - '*'
  syncWindows:
  - applications:
    - '*'
    clusters:
    - '*'
    duration: 1h
    kind: allow
    manualSync: true
    namespaces:
    - '*'
    schedule: '* * * * *'
    timeZone: America/Edmonton
