apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-longhorn-helm
  namespace: argocd
stringData:
  name: longhorn
  project: default
  type: helm
  url: https://charts.longhorn.io
