apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-metallb-helm
  namespace: argocd
stringData:
  name: metallb
  project: default
  type: helm
  url: https://metallb.github.io/metallb
