apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: memos
  namespace: memos
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`memos.redcomet.ca`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: memos
      port: 5230
